import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { openDb } from '../src/db/connection.js';
import { HashEmbeddings } from '../src/domain/embeddings.js';
import { ProjectResolver } from '../src/domain/project.js';
import { dumpMemory } from '../src/dump.js';
import { MemoryApi } from '../src/tools/api.js';

const tmpDirs: string[] = [];

function tmpDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-journal-dump-'));
  tmpDirs.push(dir);
  return dir;
}

function makeApi() {
  const dir = tmpDir();
  vi.stubEnv('XDG_CONFIG_DIR', path.join(dir, 'config'));
  const dbFile = path.join(dir, 'memory.db');
  const db = openDb(dbFile);
  const resolver = new ProjectResolver(db, dir);
  const api = new MemoryApi({ db, resolver, embeddings: new HashEmbeddings(), dbFile, random: () => 1 });
  return { dir, db, resolver, api };
}

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllEnvs();
  for (const dir of tmpDirs.splice(0)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

describe('markdown dump', () => {
  it('writes entity files and per-day journal files under .agents', async () => {
    const { dir, db, resolver, api } = makeApi();
    const entity = await api.upsertEntity({
      type: 'Service',
      title: 'Auth API',
      tags: ['auth'],
      summary: 'Handles login and sessions.',
    });
    const journal = await api.appendJournal({
      narrative: 'Verified the runtime version',
      commands: ['node --version'],
    });
    const verified = await api.addStatement({
      entity_id: entity.id,
      claim: 'Auth API runs on Node 20',
      confidence_level: 'verified',
      confidence_reason: 'checked in this session',
      derivation_method: 'command-output',
      citations: ['package.json'],
      journal_entry_id: journal.id,
    });
    const stale = await api.addStatement({
      entity_id: entity.id,
      claim: 'Auth API listens on port 3000',
      confidence_level: 'low',
      confidence_reason: 'guessed',
      derivation_method: 'inference',
    });
    await api.invalidate({ id: stale.statement.id, note: 'port changed' });

    const result = dumpMemory(db, resolver, dir);

    expect(result.entities).toBe(1);
    expect(result.statements).toBe(2);
    // The explicit journal entry plus the auto-stub from the second statement.
    expect(result.journalEntries).toBe(2);

    const entityFile = fs.readFileSync(path.join(dir, '.agents', 'knowledge-base', 'auth-api.md'), 'utf8');
    expect(entityFile.split('\n')[1]).toBe(
      '# Autogenerated by `agent-journal --dump`. Do not edit: changes are overwritten on the next dump.',
    );
    expect(entityFile).toContain(`id: ${entity.id}`);
    expect(entityFile).toContain('# Auth API');
    expect(entityFile).toContain('Handles login and sessions.');
    expect(entityFile).toContain('### Auth API runs on Node 20');
    expect(entityFile).toContain('- Confidence: verified (command-output) — checked in this session');
    expect(entityFile).toContain('- Citations: package.json');
    expect(entityFile).toContain('## Invalid statements');
    expect(entityFile).toContain('- Status: invalid — port changed');

    const day = new Date(journal.created_at).toISOString().slice(0, 10);
    const journalFile = fs.readFileSync(path.join(dir, '.agents', 'journal', `${day}.md`), 'utf8');
    expect(journalFile.split('\n')[1]).toBe(
      '# Autogenerated by `agent-journal --dump`. Do not edit: changes are overwritten on the next dump.',
    );
    expect(journalFile).toContain(`# Journal — ${day}`);
    expect(journalFile).toContain('Verified the runtime version');
    expect(journalFile).toContain('- `node --version`');
    expect(journalFile).toContain(`created: statement ${verified.statement.id}`);
    expect(journalFile).toContain('(auto-stub)');
  });

  it('replaces stale markdown files and dedupes slug collisions', async () => {
    const { dir, db, resolver, api } = makeApi();
    await api.upsertEntity({ type: 'Service', title: 'Auth API' });
    await api.upsertEntity({ type: 'Concept', title: 'Auth API' });

    const kbDir = path.join(dir, '.agents', 'knowledge-base');
    fs.mkdirSync(kbDir, { recursive: true });
    fs.writeFileSync(path.join(kbDir, 'stale-entity.md'), 'left over from a previous dump');
    fs.writeFileSync(path.join(kbDir, 'notes.txt'), 'not managed by the dump');

    const result = dumpMemory(db, resolver, dir);

    expect(result.entities).toBe(2);
    expect(fs.existsSync(path.join(kbDir, 'auth-api.md'))).toBe(true);
    expect(fs.existsSync(path.join(kbDir, 'auth-api-2.md'))).toBe(true);
    expect(fs.existsSync(path.join(kbDir, 'stale-entity.md'))).toBe(false);
    // Non-markdown files are not the dump's to delete.
    expect(fs.existsSync(path.join(kbDir, 'notes.txt'))).toBe(true);
  });

  it('dumps only the project resolved from the working directory', async () => {
    const { dir, db, resolver, api } = makeApi();
    await api.upsertEntity({ type: 'Service', title: 'Local Entity' });
    await api.upsertEntity({ type: 'Service', title: 'Foreign Entity', project: 'some-other-project' });
    await api.appendJournal({ narrative: 'foreign work', project: 'some-other-project' });

    const result = dumpMemory(db, resolver, dir);

    expect(result.entities).toBe(1);
    expect(result.journalEntries).toBe(0);
    const kbDir = path.join(dir, '.agents', 'knowledge-base');
    expect(fs.existsSync(path.join(kbDir, 'local-entity.md'))).toBe(true);
    expect(fs.existsSync(path.join(kbDir, 'foreign-entity.md'))).toBe(false);
  });

  it('handles an empty project by creating empty directories', () => {
    const { dir, db, resolver } = makeApi();
    const result = dumpMemory(db, resolver, dir);

    expect(result.entities).toBe(0);
    expect(result.journalEntries).toBe(0);
    expect(result.filesWritten).toBe(0);
    expect(fs.readdirSync(path.join(dir, '.agents', 'knowledge-base'))).toEqual([]);
    expect(fs.readdirSync(path.join(dir, '.agents', 'journal'))).toEqual([]);
  });
});
