import fs from 'node:fs';
import path from 'node:path';
import type Database from 'better-sqlite3';
import type { ProjectResolver } from './domain/project.js';

type EntityRow = {
  id: string;
  type: string;
  title: string;
  summary: string | null;
  tags: string | null;
  created_at: number;
  last_updated_at: number;
  status: string;
  invalidation_note: string | null;
  superseded_by: string | null;
};

type StatementRow = {
  id: string;
  entity_id: string;
  claim: string;
  confidence_level: string;
  confidence_reason: string;
  derivation_method: string;
  citations: string | null;
  created_at: number;
  valid_from: number | null;
  valid_to: number | null;
  status: string;
  invalidation_note: string | null;
  superseded_by: string | null;
};

type JournalRow = {
  id: string;
  created_at: number;
  commands: string | null;
  narrative: string | null;
  is_stub: number;
};

type RelationshipRow = {
  id: string;
  from_entity: string;
  to_entity: string;
  type: string;
  confidence_level: string;
  status: string;
};

type LinkRow = {
  journal_id: string;
  target_type: string;
  target_id: string;
  role: string;
};

export type DumpResult = {
  kbDir: string;
  journalDir: string;
  entities: number;
  statements: number;
  journalEntries: number;
  relationships: number;
  filesWritten: number;
};

const GENERATED_NOTICE =
  'Autogenerated by `agent-journal --dump`. Do not edit: changes are overwritten on the next dump.';

function iso(ms: number): string {
  return new Date(ms).toISOString();
}

function singleLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

function slugify(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || 'entity';
}

function parseArray(json: string | null): string[] {
  if (!json) return [];
  try {
    const value = JSON.parse(json) as unknown;
    return Array.isArray(value) ? value.map(String) : [];
  } catch {
    return [];
  }
}

// The dump owns the .md files in its output directories: every run rewrites
// the full set, so stale files from renamed or deleted records disappear.
// Non-markdown files are left alone.
function resetMarkdownDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
  for (const file of fs.readdirSync(dir)) {
    if (file.endsWith('.md')) {
      fs.rmSync(path.join(dir, file));
    }
  }
}

function blockquote(text: string): string {
  return text
    .split('\n')
    .map((line) => `> ${line}`)
    .join('\n');
}

function statementMarkdown(statement: StatementRow): string {
  const headline = singleLine(statement.claim);
  const truncated = headline.length > 80;
  const lines: string[] = [`### ${truncated ? `${headline.slice(0, 80)}…` : headline}`];
  if (truncated || statement.claim.includes('\n')) {
    lines.push('', blockquote(statement.claim));
  }
  lines.push(
    '',
    `- Id: ${statement.id}`,
    `- Confidence: ${statement.confidence_level} (${statement.derivation_method}) — ${singleLine(statement.confidence_reason)}`,
  );
  const citations = parseArray(statement.citations);
  if (citations.length > 0) {
    lines.push(`- Citations: ${citations.join(', ')}`);
  }
  lines.push(`- Created: ${iso(statement.created_at)}`);
  if (statement.valid_from !== null || statement.valid_to !== null) {
    const from = statement.valid_from !== null ? iso(statement.valid_from) : '…';
    const to = statement.valid_to !== null ? iso(statement.valid_to) : '…';
    lines.push(`- Valid: ${from} → ${to}`);
  }
  if (statement.status !== 'active') {
    const redirect = statement.superseded_by ? ` (superseded by ${statement.superseded_by})` : '';
    const note = statement.invalidation_note ? ` — ${singleLine(statement.invalidation_note)}` : '';
    lines.push(`- Status: invalid${redirect}${note}`);
  }
  return lines.join('\n');
}

function entityMarkdown(entity: EntityRow, statements: StatementRow[]): string {
  const tags = parseArray(entity.tags);
  const lines: string[] = [
    '---',
    `# ${GENERATED_NOTICE}`,
    `id: ${entity.id}`,
    `type: ${singleLine(entity.type)}`,
    `status: ${entity.status}`,
    ...(tags.length > 0 ? [`tags: [${tags.map(singleLine).join(', ')}]`] : []),
    `created: ${iso(entity.created_at)}`,
    `updated: ${iso(entity.last_updated_at)}`,
    '---',
    '',
    `# ${singleLine(entity.title)}`,
  ];
  if (entity.status !== 'active') {
    const redirect = entity.superseded_by ? ` (superseded by ${entity.superseded_by})` : '';
    const note = entity.invalidation_note ? `: ${singleLine(entity.invalidation_note)}` : '';
    lines.push('', `> Invalidated${redirect}${note}`);
  }
  if (entity.summary) {
    lines.push('', entity.summary.trim());
  }

  const active = statements.filter((statement) => statement.status === 'active');
  const invalid = statements.filter((statement) => statement.status !== 'active');
  if (active.length > 0) {
    lines.push('', '## Statements');
    for (const statement of active) {
      lines.push('', statementMarkdown(statement));
    }
  }
  if (invalid.length > 0) {
    lines.push('', '## Invalid statements');
    for (const statement of invalid) {
      lines.push('', statementMarkdown(statement));
    }
  }
  return `${lines.join('\n')}\n`;
}

function journalDayMarkdown(day: string, entries: JournalRow[], links: Map<string, LinkRow[]>): string {
  const lines: string[] = ['---', `# ${GENERATED_NOTICE}`, `date: ${day}`, '---', '', `# Journal — ${day}`];
  for (const entry of entries) {
    const stub = entry.is_stub ? ' (auto-stub)' : '';
    lines.push('', `## ${iso(entry.created_at).slice(11, 19)} UTC — ${entry.id}${stub}`);
    if (entry.narrative) {
      lines.push('', entry.narrative.trim());
    }
    const commands = parseArray(entry.commands);
    if (commands.length > 0) {
      lines.push('', '- Commands:');
      for (const command of commands) {
        lines.push(`  - \`${command}\``);
      }
    }
    const entryLinks = links.get(entry.id) ?? [];
    if (entryLinks.length > 0) {
      lines.push('', '- Links:');
      for (const link of entryLinks) {
        lines.push(`  - ${link.role}: ${link.target_type} ${link.target_id}`);
      }
    }
  }
  return `${lines.join('\n')}\n`;
}

function relationshipsMarkdown(relationships: RelationshipRow[]): string {
  const lines: string[] = [`<!-- ${GENERATED_NOTICE} -->`, '', '# Relationships', ''];
  for (const relationship of relationships) {
    const invalid = relationship.status !== 'active' ? ' (invalid)' : '';
    lines.push(
      `- ${relationship.id}: ${relationship.from_entity} —${singleLine(relationship.type)}→ ${relationship.to_entity} · ${relationship.confidence_level}${invalid}`,
    );
  }
  return `${lines.join('\n')}\n`;
}

export function dumpMemory(db: Database.Database, resolver: ProjectResolver, baseDir: string): DumpResult {
  const project = resolver.resolve();
  const kbDir = path.join(baseDir, '.agents', 'knowledge-base');
  const journalDir = path.join(baseDir, '.agents', 'journal');
  resetMarkdownDir(kbDir);
  resetMarkdownDir(journalDir);

  const entities = db
    .prepare('SELECT * FROM entity WHERE project_id = ? ORDER BY created_at, id')
    .all(project.id) as EntityRow[];
  const statements = db
    .prepare('SELECT * FROM statement WHERE project_id = ? ORDER BY created_at, id')
    .all(project.id) as StatementRow[];
  const statementsByEntity = new Map<string, StatementRow[]>();
  for (const statement of statements) {
    const list = statementsByEntity.get(statement.entity_id);
    if (list) {
      list.push(statement);
    } else {
      statementsByEntity.set(statement.entity_id, [statement]);
    }
  }

  let filesWritten = 0;
  const usedSlugs = new Map<string, number>();
  for (const entity of entities) {
    const slug = slugify(entity.title);
    const seen = (usedSlugs.get(slug) ?? 0) + 1;
    usedSlugs.set(slug, seen);
    const fileName = seen === 1 ? `${slug}.md` : `${slug}-${seen}.md`;
    fs.writeFileSync(path.join(kbDir, fileName), entityMarkdown(entity, statementsByEntity.get(entity.id) ?? []));
    filesWritten += 1;
  }

  const relationships = db
    .prepare('SELECT * FROM relationship WHERE project_id = ? ORDER BY created_at, id')
    .all(project.id) as RelationshipRow[];
  if (relationships.length > 0) {
    fs.writeFileSync(path.join(kbDir, 'relationships.md'), relationshipsMarkdown(relationships));
    filesWritten += 1;
  }

  const journalEntries = db
    .prepare('SELECT * FROM journal_entry WHERE project_id = ? ORDER BY created_at, id')
    .all(project.id) as JournalRow[];
  const links = db
    .prepare(
      `SELECT l.journal_id, l.target_type, l.target_id, l.role
       FROM journal_link l JOIN journal_entry j ON j.id = l.journal_id
       WHERE j.project_id = ?
       ORDER BY l.journal_id, l.target_type, l.target_id, l.role`,
    )
    .all(project.id) as LinkRow[];
  const linksByJournal = new Map<string, LinkRow[]>();
  for (const link of links) {
    const list = linksByJournal.get(link.journal_id);
    if (list) {
      list.push(link);
    } else {
      linksByJournal.set(link.journal_id, [link]);
    }
  }

  const entriesByDay = new Map<string, JournalRow[]>();
  for (const entry of journalEntries) {
    const day = iso(entry.created_at).slice(0, 10);
    const list = entriesByDay.get(day);
    if (list) {
      list.push(entry);
    } else {
      entriesByDay.set(day, [entry]);
    }
  }
  for (const [day, entries] of entriesByDay) {
    fs.writeFileSync(path.join(journalDir, `${day}.md`), journalDayMarkdown(day, entries, linksByJournal));
    filesWritten += 1;
  }

  return {
    kbDir,
    journalDir,
    entities: entities.length,
    statements: statements.length,
    journalEntries: journalEntries.length,
    relationships: relationships.length,
    filesWritten,
  };
}
